# Generated by Django 5.0.6 on 2025-08-12 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobdescription_generationjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('profile', 'Profile'), ('ai', 'AI'), ('system', 'System')], max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='api_auditlo_categor_427ac4_idx'), models.Index(fields=['user', 'created_at'], name='api_auditlo_user_id_b608a1_idx')],
            },
        ),
    ]
