version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: resumeai
      POSTGRES_USER: resumeai
      POSTGRES_PASSWORD: resumeai
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    command: sh -c "./docker-entrypoint.sh"
    env_file: .env
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  pgdata:
